# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dc5a81eddbdbc271564ba3aea73085b0d09178d8b04f13ae8d7cbb7df158aebfc066f8ec1c54b9c31d0c799f1f7772884cf4e57ffa470ad148daacc00a8898d

test:
  secret_key_base: ff3547dd64aa0f434474a72851b6073b355ca7e702c5bb06b24ca1b4e447f259bbb65394227d3035180491ace8b5c6eafca206852795d0d448fcc7b67ac7346d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
